project/urls.py
from video import views as video_views
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', video_views.home),
    path('catalog/', video_views.catalog),
    path('watch/', video_views.watch_video),
    path('upload/', video_views.upload_video),
    path('catalog/delete/', video_views.delete_video),
    path('tags/', video_views.get_tags),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/models.py
from django.db import models
from django.dispatch.dispatcher import receiver
import shutil
from os import path
from django.conf import settings

class VideoUnit(models.Model):
    """ Видео как целый объект """
    title = models.CharField(max_length=255)

    def get_root_dir(self):
        return str(self.id)

        
def videofile_path(instance, filename):
    return f'{instance.videounit.get_root_dir()}/{filename}'

@receiver(models.signals.pre_delete, sender=VideoUnit)
def auto_delete_videounit(sender, instance, **kwargs):
    if instance.videofile and instance.videofile.file:
        instance.videofile.file.delete()
    if instance.videothumbnail and instance.videothumbnail.file:
        instance.videothumbnail.file.delete()

    shutil.rmtree(path.join(settings.MEDIA_ROOT, instance.get_root_dir()))

class VideoFile(models.Model):
    """ Видео как файл """
    file = models.FileField(upload_to=videofile_path, null=False)
    videounit = models.OneToOneField(VideoUnit, on_delete=models.CASCADE,
        primary_key=True)
    
    def __str__(self):
        return self.file.name

def videothumbnail_path(instance, filename):
    return f'{instance.videounit.get_root_dir()}/{filename}'

class VideoThumbnail(models.Model):
    """ Миниатюрное изображение для видео """
    file = models.ImageField(upload_to=videothumbnail_path, null=True)
    videounit = models.OneToOneField(VideoUnit, on_delete=models.CASCADE,
        primary_key=True)

class VideoTag(models.Model):
    """ Теги для видео """
    name = models.CharField(max_length=255)
    videounits = models.ManyToManyField(VideoUnit)
    
    def __str__(self):
        return self.name

video/models/codec.py
from django.db import models

class VideoCodec(models.Model):
    name = models.CharField(max_length=255)

class AudioCodec(models.Model):
    name = models.CharField(max_length=255)

video/models/video.py
from .codec import AudioCodec, VideoCodec
from django.db import models
from django.dispatch.dispatcher import receiver
import shutil
from os import path
from django.conf import settings

class VideoUnit(models.Model):
    """ Видео как целый объект """
    title = models.CharField(max_length=255)
    views_count = models.BigIntegerField()
    liked_count = models.BigIntegerField()
    disliked_count = models.BigIntegerField()
    description = models.TextField()
    datetime_added = models.DateTimeField()

    def get_root_dir(self):
        return str(self.id)

        
def videofile_path(instance, filename):
    return f'{instance.videounit.get_root_dir()}/{filename}'

@receiver(models.signals.pre_delete, sender=VideoUnit)
def auto_delete_videounit(sender, instance, **kwargs):
    if instance.videofile and instance.videofile.file:
        instance.videofile.file.delete()
    if instance.videothumbnail and instance.videothumbnail.file:
        instance.videothumbnail.file.delete()

    shutil.rmtree(path.join(settings.MEDIA_ROOT, instance.get_root_dir()))

class VideoFile(models.Model):
    """ Видео как файл """
    file = models.FileField(upload_to=videofile_path, null=False)
    mime_type = models.CharField(max_length=127)
    duration = models.DurationField()
    video_codec = models.ManyToManyField(VideoCodec)
    audio_codec = models.ManyToManyField(AudioCodec)
    height = models.IntegerField()
    width = models.IntegerField()
    videounit = models.OneToOneField(VideoUnit, on_delete=models.CASCADE,
        primary_key=True)
    
    def __str__(self):
        return self.file.name

def videothumbnail_path(instance, filename):
    return f'{instance.videounit.get_root_dir()}/{filename}'

class VideoThumbnail(models.Model):
    """ Миниатюрное изображение для видео """
    file = models.ImageField(upload_to=videothumbnail_path, null=True)
    mime_type = models.CharField(max_length=127)
    height = models.IntegerField()
    width = models.IntegerField()
    videounit = models.OneToOneField(VideoUnit, on_delete=models.CASCADE,
        primary_key=True)

class VideoTag(models.Model):
    """ Теги для видео """
    name = models.CharField(max_length=255)
    videounits = models.ManyToManyField(VideoUnit)
    
    def __str__(self):
        return self.name

video/forms.py
from django.forms import widgets
# from .models import video
from django import forms

class UploadVideoForm(forms.Form):
    title = forms.CharField(label='Название', help_text='Введите название видео')
    video = forms.FileField(label='Видео', help_text='Добавьте видео')
    tags = forms.CharField(label='Теги', help_text='Выберите теги')


class DeleteVideoForm(forms.Form):
    video_id = forms.IntegerField(widget=forms.HiddenInput())

catalog/views.py
from .forms import UploadVideoForm, DeleteVideoForm
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import VideoFile, VideoUnit

def catalog(request):
    videos = VideoUnit.objects.all()
    for v in videos:
        v.delete_form = DeleteVideoForm(initial={'video_id': v.id})

    context = {
        'videos': videos,
        'add_form': UploadVideoForm(),
    }

    return render(request, 'catalog/index.html', context)

def make_error_string(form):
    error_string = ''
    for field in form:
        if field.errors:
            for error in field.errors:
                error_string += error + '\n'


def create_video(request):
    if request.method == 'POST':
        add_form = UploadVideoForm(request.POST, request.FILES)
        if add_form.is_valid():
            title = add_form.cleaned_data.get('title')
            video = add_form.cleaned_data.get('video')

            vu = VideoUnit.objects.create(title=title)
            vu.save()

            vf = VideoFile.objects.create(videounit=vu, file=video)
            vf.save()

            return HttpResponseRedirect('../')

        return HttpResponse(make_error_string(add_form))

def delete_video(request):
    if request.method == 'POST':
        delete_form = DeleteVideoForm(request.POST)
        if delete_form.is_valid():
            video_id = delete_form.cleaned_data.get('video_id')
            VideoUnit.objects.filter(id=video_id).delete()
            return HttpResponseRedirect('../')
        
        return HttpResponse(make_error_string(delete_form))

    return HttpResponseRedirect('../')

video/views.py
from .forms import UploadVideoForm, DeleteVideoForm
from django.http.response import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from .models import video
from . import services
import json

def home(request):
    return render(request, 'video/home.html')

def catalog(request):
    videos = video.VideoUnit.objects.all()
    for v in videos:
        v.delete_form = DeleteVideoForm(initial={'video_id': v.id})
        v.tags = list(v.videotag_set.all().values('name'))

    context = {'videos': videos}
    return render(request, 'video/catalog.html', context)

def watch_video(request):
    video_id = request.GET.get('id', '')
    if not video_id:
        return HttpResponseNotFound('Not Found')
    video_id = int(video_id)

    v = video.VideoUnit.objects.get(id=video_id)
    if not v:
        return HttpResponseNotFound('Not Found')
    
    context = {'video': v}
    return render(request, 'video/watch.html', context)

def upload_video(request):
    if request.method == 'POST':
        form = UploadVideoForm(request.POST, request.FILES)
        if form.is_valid():
            services.create_videounit(
                title=form.cleaned_data.get('title'),
                video=form.cleaned_data.get('video'),
                tags=json.loads(form.cleaned_data.get('tags')),
            )
            
            return HttpResponseRedirect('/catalog')
        return HttpResponse(services.get_errors_with_form(form))

    elif request.method == 'GET':
        context = {
            'upload_form': UploadVideoForm(),
        }
        return render(request, 'video/upload.html', context)

def delete_video(request):
    if request.method == 'POST':
        delete_form = DeleteVideoForm(request.POST)
        if delete_form.is_valid():
            video_id = delete_form.cleaned_data.get('video_id')
            video.VideoUnit.objects.filter(id=video_id).delete()
            return HttpResponseRedirect('/catalog')
        
        return HttpResponse(services.get_errors_with_form(delete_form))

    return HttpResponseRedirect('/catalog')

def get_tags(request):
    tags = video.VideoTag.objects.all()

    tags_dict = {'tags': [], 'count': 0}
    for tag in tags:
        tags_dict['tags'].append({
            'name': tag.name,
            'id': tag.id,
        })
        tags_dict['count'] += 1
    tags_json = json.dumps(tags_dict, indent=4, ensure_ascii=False)
        
    return HttpResponse(tags_json, content_type='application/json; charset=utf-8')

templates/video/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock title %}</title>
    <style>
        body {
            font-family: 'Courier New', Courier, monospace;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            --sidenav-width: 75px;
        }
        .content {
            padding: 10px 20px;
            margin-left: var(--sidenav-width);
        }

        /* Side navigation */
        .sidenav {
            display: flex;
            flex-direction: column;
            border-right: 1px solid lightgrey;
            width: var(--sidenav-width);
            height: 100%;
            position: fixed;
            top: 0;
            left: 0;
        }
        .sidenav > a {
            margin: 10px 0;
            color: grey;
            text-align: center;
        }
        .sidenav > a:hover {color: rgb(49, 49, 49)}
        /* End side navigation */
    </style>
    {% block header %}{% endblock header %}
</head>
<body>
    <div class="sidenav">
        <a href="/">Home</a>
        <a href="#">Tags</a>
        <a href="/catalog">Videos</a>
    </div>

    <div class="content">{% block content %}{% endblock content %}</div>
</body>
</html>

templates/video/catalog.html
{% extends "video/base.html" %}
{% load static %}

{% block title %}Videos{% endblock title %}

{% block header %}
<style>
    .controls {
        display: grid;
        margin-bottom: 40px;
    }

    .button {
        border: none;
        color: white;
        padding: 8px 16px;
        border-radius: 20px;
        cursor: pointer;
    }
    .red { background: #f23f3f; }
    .blue { background: #50b3d4; }

    .tags { display: flex; }
    .tag {
        font-size: 12px;
        background: lightgrey;
        padding: 3px 6px;
        border-radius: 2px;
        margin: 3px 6px;
    }

    .videos-table {
        width: 100%;
        border-collapse: collapse;
    }
    .videos-table tbody td:first-child {
        width: 120px;
        text-align: center;
    }
    .videos-table tbody td:nth-child(2) { padding-left: 20px; }
    .controls {
        display: flex;
        justify-content: space-evenly;
    }
    .control-button {
        border-radius: 2px;
        padding: 4px 8px;
    }

    .thumbnail {
        height: 90px;
        width: 90px;
    }
</style>
{% endblock header %}

{% block content %}
<div class="controls">
    <a href="/upload"><button>+ Add video</button></a>
</div>

<table class="videos-table" border bordercolor="lightgrey">
    <caption><h3>Video list</h3></caption>
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Tags</th>
            <th style="width: 120px">Image</th>
            <th style="width: 20%">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for v in videos %}
        <tr>
            <td>{{ v.id }}</td>
            <td>{{ v.title }}</td>
            <td>
                <div class="tags">
                    {% for t in v.tags %}
                    <span class="tag">{{ t.name }}</span>
                    {% endfor %}
                </div>
            </td>
            <td style="text-align: center;">
                <img class="thumbnail" src="{{ v.videothumbnail.file.url }}">
            </td>
            <td>
                <div class="controls">
                    <div>
                        <a href="/watch?id={{ v.id }}">
                            <button class="control-button button blue">Watching</button>
                        </a>
                    </div>
                    <div>
                        <form action="delete/" method="POST">
                            {% csrf_token %}
                            {{ v.delete_form }}
                            <button class="control-button button red" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script src="{% static 'js/clear-forms.js' %}"></script>
{% endblock content %}

templates/video/home.html
{% extends "video/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block header %}{% endblock header %}

{% block content %}
<h1>Home</h1>
{% endblock content %}

templates/video/upload.html
{% extends "video/base.html" %}
{% load static %}

{% block title %}Add video{% endblock title %}

{% block header %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.1.1/tagify.min.css" crossorigin="anonymous" />
<style>
    hr {
        border: none;
        background: lightgrey;
        color: lightgrey;
        height: 1px;
    }

    input[type="text"] { width: 100%; }
    input {
        margin-top: 10px;
        margin-bottom: 20px
    }
    .upload-form {
        margin-top: 10px;
        width: 600px;
        border: 1px solid lightgray;
        padding: 20px;
    }
</style>
{% endblock header %}

{% block content %}
<nav>
    <a href="../"><button><- Назад</button></a>
</nav>

<h1>Добавление видео</h1>
<span>Для добавления видео заполните форму ниже и нажмите на кнопку "Загрузить"</span>

<div class="upload-form">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {% for field in upload_form %}
            <div class="form-group">
                {{ field.label_tag }}
                <div>{{ field }}</div>
            </div>
            {% endfor %}
        </div>
        <hr>
        <div style="text-align: right;">
            <input type="submit" style="cursor: pointer;" value="Загрузить">
        </div>
    </form>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.1.1/tagify.min.js"></script>
<script src="{% static 'js/clear-forms.js' %}"></script>
<script>
    const inputElement = document.querySelector('#id_tags')
    let tagify

    function renameKey(obj, oldKey, newKey) {
        const clonedObj = Object.assign({}, obj)
        const targetKey = clonedObj[oldKey]

        delete clonedObj[oldKey]
        clonedObj[newKey] = targetKey
        return clonedObj
    }

    // Update tags
    (async() => {
        const response = await fetch('/tags')
        const json = await response.json()
        const tags = json.tags

        const whitelist = []

        for (let tag of tags)
            whitelist.push(renameKey(tag, 'name', 'value'))

        tagify = new Tagify(inputElement, {
            whitelist,
            maxTags: 32,
            dropdown: {
                position: "manual",
                maxItems: 5,
                enabled: 0,
                classname: "customSuggestionsList",
            },
            // enforceWhitelist: true,
        })

        tagify.dropdown.show.call(tagify)
        tagify.DOM.scope.parentNode.appendChild(tagify.DOM.dropdown)
    })()
</script>
{% endblock content %}

templates/video/watch.html
{% extends "video/base.html" %}
{% load static %}

{% block title %}{{ video.title }}{% endblock title %}

{% block header %}
<style>
    nav { margin-bottom: 20px; }
    video {
        height: 300px;
        width: 500px;
        object-fit: cover;
    }
    h3 {
        padding: 0; 
        margin: 0;
    }
</style>
{% endblock header %}

{% block content %}
<nav>
    <a href="/catalog"><button><- Go to catalog</button></a>
</nav>
<video src="{{ video.videofile.file.url }}" controls></video>
<h3>{{ video.title }}</h3>
{% endblock content %}